
name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  go_router: ^17.0.1
  http: ^1.2.1
  google_fonts: ^7.0.2
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3
  flutter_local_notifications: ^19.5.0
  camera: ^0.11.0
  image_picker: ^1.1.2
  firebase_ai: ^3.6.1
  purchases_flutter: ^9.10.6
  image: ^4.2.0
  smooth_page_indicator: ^2.0.1
  package_info_plus: ^9.0.0
  in_app_review: ^2.0.8
  url_launcher: ^6.3.0
  mobile_scanner: ^7.1.4
  permission_handler: ^12.0.1
  pdf: ^3.10.8
  printing: ^5.11.1
  timezone: ^0.10.1
  logging: ^1.3.0
  fl_chart: ^1.1.1
  sqflite: ^2.3.0
  path: ^1.9.0
  speech_to_text: ^7.3.0
  shimmer: ^3.0.0
  vibration: ^3.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.11
  mockito: ^5.4.4
  fake_async: ^1.3.1
  firebase_auth_mocks: ^0.15.1
  firebase_core_platform_interface: ^6.0.2


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
