
name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  go_router: ^14.1.1
  http: ^1.2.1
  google_fonts: ^6.2.1
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.1
  flutter_local_notifications: ^17.1.2
  camera: ^0.11.0
  image_picker: ^1.1.2
  firebase_vertexai: ^0.2.0
  purchases_flutter: ^8.0.0
  image: ^4.2.0
  smooth_page_indicator: ^1.1.0
  package_info_plus: ^8.0.0
  in_app_review: ^2.0.8
  url_launcher: ^6.3.0
  mobile_scanner: ^6.0.0
  permission_handler: ^11.3.0
  pdf: ^3.10.8
  printing: ^5.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  mockito: ^5.4.4
  fake_async: ^1.3.1


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
